#!/bin/bash


# colon test1 dataset voting

python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon.yaml logger.wandb.tags=['trust','voting','sub_prob','colon','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=10
python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon.yaml logger.wandb.tags=['trust','voting','sub_prob','colon','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=30
python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon.yaml logger.wandb.tags=['trust','voting','sub_prob','colon','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=50
python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon.yaml logger.wandb.tags=['trust','voting','sub_prob','colon','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=70
python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon.yaml logger.wandb.tags=['trust','voting','sub_prob','colon','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=90
python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon.yaml logger.wandb.tags=['trust','voting','sub_prob','colon','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=100
python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon.yaml logger.wandb.tags=['trust','voting','sub_prob','colon','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=200


# colon test2 dataset voting
python ../test.py model.name='vit_base_r50_s16_384' model=voting2.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon_test2.yaml logger.wandb.tags=['trust','voting','sub_prob','colon_test2','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=10
python ../test.py model.name='vit_base_r50_s16_384' model=voting2.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon_test2.yaml logger.wandb.tags=['trust','voting','sub_prob','colon_test2','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=30
python ../test.py model.name='vit_base_r50_s16_384' model=voting2.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon_test2.yaml logger.wandb.tags=['trust','voting','sub_prob','colon_test2','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=50
python ../test.py model.name='vit_base_r50_s16_384' model=voting2.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon_test2.yaml logger.wandb.tags=['trust','voting','sub_prob','colon_test2','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=70
python ../test.py model.name='vit_base_r50_s16_384' model=voting2.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon_test2.yaml logger.wandb.tags=['trust','voting','sub_prob','colon_test2','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=90
python ../test.py model.name='vit_base_r50_s16_384' model=voting2.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon_test2.yaml logger.wandb.tags=['trust','voting','sub_prob','colon_test2','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=100
python ../test.py model.name='vit_base_r50_s16_384' model=voting2.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=colon_test2.yaml logger.wandb.tags=['trust','voting','sub_prob','colon_test2','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.09534 model.sampling='trust' model.num_sample=200


# gastric dataset voting
taskset -c 128-255 python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=gastric2.yaml logger.wandb.tags=['trust','voting','sub_prob','gastric','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/gastric/classifycompare/vit_base_r50_s16_384/2023-05-25_02-15-37/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.08 model.sampling='trust' model.num_sample=10
taskset -c 128-255 python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=gastric2.yaml logger.wandb.tags=['trust','voting','sub_prob','gastric','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/gastric/classifycompare/vit_base_r50_s16_384/2023-05-25_02-15-37/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.08 model.sampling='trust' model.num_sample=30
taskset -c 128-255 python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=gastric2.yaml logger.wandb.tags=['trust','voting','sub_prob','gastric','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/gastric/classifycompare/vit_base_r50_s16_384/2023-05-25_02-15-37/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.08 model.sampling='trust' model.num_sample=50
taskset -c 128-255 python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=gastric2.yaml logger.wandb.tags=['trust','voting','sub_prob','gastric','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/gastric/classifycompare/vit_base_r50_s16_384/2023-05-25_02-15-37/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.08 model.sampling='trust' model.num_sample=70
taskset -c 128-255 python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=gastric2.yaml logger.wandb.tags=['trust','voting','sub_prob','gastric','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/gastric/classifycompare/vit_base_r50_s16_384/2023-05-25_02-15-37/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.08 model.sampling='trust' model.num_sample=90
taskset -c 128-255 python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=gastric2.yaml logger.wandb.tags=['trust','voting','sub_prob','gastric','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/gastric/classifycompare/vit_base_r50_s16_384/2023-05-25_02-15-37/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.08 model.sampling='trust' model.num_sample=100
taskset -c 128-255 python ../test.py model.name='vit_base_r50_s16_384' model=voting.yaml model.vote_score_way='relative' model.weighted_sum=True model.decide_by_total_probs=False logger.wandb.project='vit_base_relative_weighted_sum' trainer.devices=[3] datamodule=gastric2.yaml logger.wandb.tags=['trust','voting','sub_prob','gastric','10%'] ckpt_path="../scripts/scripts/logs/experiments/runs/gastric/classifycompare/vit_base_r50_s16_384/2023-05-25_02-15-37/checkpoints/epoch_*.ckpt" model.key='sub_prob' model.threshold=0.08 model.sampling='trust' model.num_sample=200
